apiVersion: v2
name: cert-manager
description: A Helm wrapper chart for cert-manager with Kubeflow platform defaults
version: 0.1.0
appVersion: v1.20.2
keywords:
- cert-manager
- kubeflow
- certificates
home: https://github.com/kubeflow/community-distribution
sources:
- https://cert-manager.io
- https://github.com/kubeflow/community-distribution/tree/master/common/cert-manager
dependencies:
- name: cert-manager
  version: "1.20.2"
  repository: https://charts.jetstack.io
  condition: cert-manager.enabled
annotations:
  category: Security
  licenses: Apache-2.0
